site_name: "DataScience with Python"
pages:
- "Home": 'index.md'
- "IO": 'io.md'
- "Preparation": 'preparation.md'
- "Transformation": 'transformation.md'
markdown_extensions:
    - footnotes
